### ISSUE TITLE
TimeoutError is thrown on retrieval of own ip address

### ISSUE THREAD

**Issue by Sebisnow** [constverum/ProxyBroker#25] opened 2016-10-18 10:42 UTC
I encountered a new error stating: "Could not get a external IP.".

I took a look around to figure out if I can fix it or if I caused the error somehow. To me it looks like proxybroker tries to connect to "http://httpbin.org/ip" but the timeout of 3 seconds fails. I checked whether the mentioned website was working properly. It is up and running with fast response times.
I tried running proxybroker on a server, to check whether or not it is a local problem with the same error popping up.
The funny thing is sometimes proxybroker actually fetched a few proxies before the following error was thrown.

Do you have any idea what else could cause this error, but the website? And more important, how to fix this issue?

Any feedback is appreciated!

```
/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/aiohttp/client.py:494: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/proxybroker/utils.py", line 101, in set_my_ip
    data = await resp.json()
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/async_timeout/__init__.py", line 44, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/testing/test/test_prox2.py", line 19, in <module>
    loop.run_until_complete(tasks)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/proxybroker/api.py", line 98, in find
    await set_my_ip(self._timeout, self._loop)
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/proxybroker/utils.py", line 103, in set_my_ip
    raise RuntimeError('Could not get an external IP. Error: %s' % e)
RuntimeError: Could not get an external IP. Error: 
Exception ignored in: <coroutine object show at 0x7f9b22cdd150>
Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/testing/test/test_prox2.py", line 7, in show
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed


Process finished with exit code 1
```

**Comment by th3l0b3** [comment] 2016-10-20 13:26
same issue here as well.

**Comment by Sebisnow** [comment] 2016-10-20 17:47
The funny thing is, that the error occurs very often but not all the time. Today proxybroker worked fine for once. On the next try the error reoccurred!

**Comment by gabrielgradinaru** [comment] 2017-09-19 18:08
This issue is very old and the traceback does not reflect the current code.
I suggest closing this and reopen if the error appears again.

**Comment by trevoryann** [comment] 2017-09-19 23:15
I am seeing this issue intermittently with version 0.2.0:

Traceback (most recent call last):
  File "/home/trevor/.local/lib/python3.5/site-packages/proxybroker/resolver.py", line 67, in get_real_ext_ip
    session.get('http://httpbin.org/ip') as resp:
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/client.py", line 231, in _request
    conn = yield from self._connector.connect(req)
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 378, in connect
    proto = yield from self._create_connection(req)
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 687, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 698, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 669, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/trevor/.local/lib/python3.5/site-packages/aiohttp/resolver.py", line 31, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trevor/.local/lib/python3.5/site-packages/proxybroker/resolver.py", line 68, in get_real_ext_ip
    data = await resp.json()
  File "/home/trevor/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 37, in __exit__
    self._do_exit(exc_type)
  File "/home/trevor/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 72, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "findproxies.py", line 32, in <module>
    loop.run_until_complete(tasks)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/trevor/.local/lib/python3.5/site-packages/proxybroker/api.py", line 149, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/home/trevor/.local/lib/python3.5/site-packages/proxybroker/resolver.py", line 70, in get_real_ext_ip
    raise RuntimeError('Could not get a external IP. Error: %s' % e)
RuntimeError: Could not get a external IP. Error:

**Comment by constverum** [comment] 2017-09-21 13:56
@gabrielgradinaru it seems the ProxyBroker is being run from a script, not via CLI, so the fix for the CLI is unlikely could help here.
```
  File "/home/sebastian/PycharmProjects/testing/test/test_prox2.py", line 19, in <module>
    loop.run_until_complete(tasks)
```
And as I can see was used the old 0.1.4 version.
@Sebisnow if the error still occurs could you please provide full content of the `test_prox2.py` file?

**Comment by gabrielgradinaru** [comment] 2017-09-22 08:45
@constverum indeed, the fix/workaround will only work for the CLI.

Looking a bit deeper it looks like in api.py line 371, cancel() is called of a Task but as you can see in the docs:
 https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel 
> this does not guarantee that the task will be cancelled

I guess a better fix would be to wait until the Task is actually finished, I will try to find a way to do this when I will have time.

**Comment by constverum** [comment] 2017-09-22 08:52
> I guess a better fix would be to wait until the Task is actually finished, I will try to find a way to do this when I will have time.

https://github.com/constverum/ProxyBroker/blob/2612b5863b7569177dcaf9087377990ec7e48279/proxybroker/cli.py#L313-L324

Basically, we could call `broker.stop()` before stopping the loop. It will cancel the tasks correctly.
But anyway to solve this issue need to add alternative way to get external IP (in addition to httpbin.org).

**Comment by gabrielgradinaru** [comment] 2017-09-24 09:54
I agree that an alternative way do get external IP is useful here, but calling `broker.stop()` before stopping the loop is not going to help in this case. This is because `broker._done()` has already been called before in `_grab`: https://github.com/constverum/ProxyBroker/blob/2a09c0f3ca2a2cab2d392a94ddd1b8cd9adf1d42/proxybroker/api.py#L295
and the tasks have been popped from the `_all_tasks` queue:
https://github.com/constverum/ProxyBroker/blob/2a09c0f3ca2a2cab2d392a94ddd1b8cd9adf1d42/proxybroker/api.py#L368-L374

Please correct me if I'm wrong and this is not the case.
I have also tried to find a better fix than eliminating the `loop.close()` call but could not find one :cry:

**Closed** 2017-10-04 15:02 UTC
Labels: bug

**Comment by Yuraz71** [comment] 2019-09-12 03:14
Can I reopen this issue ?
In last week I be in struggle with "Could not get the external IP" exception.

Traceback (most recent call last):
  File "refresh_proxy.py", line 50, in <module>
    prox = Proxies(loop)
  File "refresh_proxy.py", line 13, in __init__
    self._init_proxies(loop)
  File "refresh_proxy.py", line 24, in _init_proxies
    loop.run_until_complete(asyncio.wait_for(tasks, 120))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/dist-packages/proxybroker/api.py", line 173, in find
    ip = await self._resolver.get_real_ext_ip()
  File "/usr/local/lib/python3.7/dist-packages/proxybroker/resolver.py", line 109, in get_real_ext_ip
    raise RuntimeError('Could not get the external IP')
RuntimeError: Could not get the external IP

I found some incomprehensibility in resolver.py.
Maybe you can explain this problem for me, and I will leave everything as it is?

So, in resolver.py I found:
    _ip_hosts = [
        'https://wtfismyip.com/text',
        'http://api.ipify.org/',
        'http://ipinfo.io/ip',
        'http://ipv4.icanhazip.com/',
        'http://myexternalip.com/raw',
        'http://ipinfo.io/ip',
        'http://ifconfig.io/ip',
    ]
After that:
        host = random.choice(self._ip_hosts)
        self._ip_hosts.remove(host)

So, when we remove last item from this list we get exception.
And this is confirmed in practice.
I try refresh proxy list every 5 minutes. After 7th times I always get exception.
I try comment this line in local machine: 
 self._ip_hosts.remove(host) 
and all works is fine.

@constverum, could you explain what is wrong ?
